// Menu
export const CLOSE_MENU = 'CLOSE_MENU';
export const OPEN_MENU = 'OPEN_MENU';

// Cart
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';

// Products
export const START_GET_PRODUCTS = 'START_GET_PRODUCTS';
export const SUCCESS_GET_PRODUCTS = 'SUCCESS_GET_PRODUCTS';
export const ERROR_GET_PRODUCTS = 'ERROR_GET_PRODUCTS';
export const START_SEARCH_PRODUCTS = 'START_SEARCH_PRODUCTS';
export const SUCCESS_SEARCH_PRODUCTS = 'SUCCESS_SEARCH_PRODUCTS';
export const ERROR_SEARCH_PRODUCTS = 'ERROR_SEARCH_PRODUCTS';

export const SHOW_HOME_SECTION = 'SHOW_HOME_SECTION';